### PR TITLE
Fix tests (see #74) and make classes Serializable

### PR DESCRIPTION
**Pull request by gangeli**
Updates the tests as described in #74, and allows for many of the objects to be Serializable.

### CODE REVIEW

**Comment by mangstadt** [comment]
Thanks for your contribution.  Why must the classes be Serializable?

**Comment by gangeli** [comment]
I'm trying to save a parsed calendar. In some sense this is a bespoke use-case, but I figure others may want to serialize their calendars as well. The only cost here is potential maintenance cost, if you want to keep classes backwards serializable. But, I'd imagine most of these classes are mature enough that their fields wouldn't change much?

**Comment by mangstadt** [comment]
It seems like to much fluff to add to the codebase.  I'm curious to know your reason for needing to use Java serialization?

**Comment by gangeli** [comment]
True, it's annoying boilerplate, but then again half of Java is annoying boilerplate :(. The performance cost of implementing Serializable is zero, and I may not be the last person to want to serialize a parsed time. Currently I'm happy on my fork too, but I figured I'd open a pull request in case it's useful to others.

**Comment by waded** [comment]
Looks like this has been open for a while. I for one can't think of why this would be useful; the biweekly library is for parsing and writing the iCalendar format, (re)parsing or (re)writing in that format is much more portable and does not put additional burden on maintenance of the library.

**Comment by mangstadt** [comment]
Thanks for your input, @waded. I agree.

**Comment by mangstadt** [comment]
Closing this pull request. This isn't something I want to add to biweekly, but thank you for contributing!

**Pull request closed without merging**
